[tool.poetry]
name = "matlib"
version = "0.1.1"
description = ""
authors = ["Denis Demenkov <deniska_demenkov@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
